---
abstract: unknown
author:
  - 'Brian Duggan <bduggan@matatu.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-SpellChecker
no_index:
  directory:
    - t
    - inc
requires:
  MIME::Base64: '0'
  Storable: '0'
  Text::Aspell: '0'
  perl: '5.010001'
resources:
  repository: https://github.com/bduggan/Text-SpellChecker.git
version: '0.12'
